apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc
  namespace: {{.Release.Namespace | quote }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name | quote }}
    app: btc
spec:
  selector:
    matchLabels:
      app: btc
  replicas: {{ .Values.image.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: btc
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: btc
              topologyKey: kubernetes.io/hostname
      containers:
        - name: btc
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - ./btc
          ports:
          - name: http
            containerPort:  9201
          env:
            - name: QUOTATIONS_HOST
              value: quotations:9200
---
apiVersion: v1
kind: Service
metadata:
  name: btc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name | quote }}
    app: btc
spec:
  type: NodePort
  ports:
  - port: 9201
    targetPort: 9201
  selector:
    app: btc
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: btc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name | quote }}
    app: btc
spec:
   maxReplicas: 10
   minReplicas: {{ .Values.image.replicaCount }}
   scaleTargetRef:
     apiVersion: apps/v1
     kind: Deployment
     name: btc
   metrics:
   - type: Resource
     resource:
       name: cpu
       targetAverageUtilization: 70
---