apiVersion: v1
kind: ConfigMap
metadata:
  name: tilt-demo
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name | quote }}
data:
  POSTGRES_PORT: {{ .Values.postgresql.postgresqlPort | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresql.postgresqlUsername }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword }}
  POSTGRES_DATABASE: {{ .Values.postgresql.postgresqlDatabase }}

  PTAX_URL: https://olinda.bcb.gov.br
  COINDECK_URL: https://api.coindesk.com/v1/bpi/currentprice/%s.json

  QUOTATIONS_HOST: :9200
  BTC_HOST: :9201